### PR TITLE
NEW Replace share draft toggle component in the CMS with React driven equivalent

### LINKED ISSUE #78: Update of UI to match SS4
Use of an icon to indicate share would be the most obvious improvement but we should also consider the alignment of the "Share" text with the "Preview mode" toggle as they look out of place next to each other. Consider react popover.

Design ACs:
 * Swap position of share icon with page mode dropdown.
 * Add suitable icon to Share Draft button (text disappears on smaller viewports so the icon needs to be descriptive).
 * Add some descriptive text as to what the link does.
 * Add user guides to module.
 * Link to User guide for more information.

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-admin/pull/563
- [x] https://github.com/silverstripe/silverstripe-admin/pull/564
- [x] https://github.com/silverstripe/silverstripe-admin/pull/565
- [ ] sharedraftcontent: #86

### PR DESCRIPTION
**Pull request by robbieaverill**
Requires https://github.com/silverstripe/silverstripe-admin/pull/563, https://github.com/silverstripe/silverstripe-admin/pull/564 and https://github.com/silverstripe/silverstripe-admin/pull/565

Resolves #78

### CODE REVIEW

**Comment by NightJar** [comment]
NPM checks appear to be having an issue dealing with externals it seems.

**Comment by robbieaverill** [comment]
There are some dependencies on this that were noted in the issue but I've copied them to here as well. I'll also need to switch to `--prefer-source` in Travis when everything is merged

**Comment by NightJar** [comment]
Ah right, ta :)
We'll I'll approve, with the usual caveat of merging when tests turn green.

**Comment by dhensby** [comment]
hmm, the NPM test didn't have a good time

**Comment by robbieaverill** [comment]
Tests are green now but please note the requirements in admin that need to be merged for this to be complete

**Comment by NightJar** [comment]
Thanks Robbie, admin [563](https://github.com/silverstripe/silverstripe-admin/pull/563) & [564](https://github.com/silverstripe/silverstripe-admin/pull/564) still remaining open at this point.

**Pull request merged**
